@currentDate = 2020-04-17T00:00:00%2B00:00
@horizon = 7

GET http://localhost:32768/deliverytimes?currentdate={{currentDate}}&horizon={{horizon}} HTTP/1.1
Content-Type: application/json
Accept: application/json

###
@start = "2020-04-17T00:00:00Z"
@finish = "2020-04-23T23:59:59Z"

POST http://localhost:32768/deliverytimes HTTP/1.1
content-type: application/json


{
    "name": "sample",
    "description": "description",
    "price": 123,
    "type": "Regular",
    "daysOfWeek": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
    "from": "18:00",
    "to": "20:00",
    "start": {{start}},
    "finish": {{finish}},
    "closesBeforeMinutes": 800
}